"""Add cascading delete events for connections and credentials

Revision ID: 058889b56728
Revises: 8881ae81b5e3
Create Date: 2025-05-06 23:28:09.410958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '058889b56728'
down_revision = '8881ae81b5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
