"""add labels

Revision ID: 1ab50fcb59fb
Revises: 456789abcdef
Create Date: 2025-03-14 14:19:33.305235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab50fcb59fb'
down_revision = '456789abcdef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destination', sa.Column('labels', sa.JSON(), nullable=True))
    op.add_column('source', sa.Column('labels', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'labels')
    op.drop_column('destination', 'labels')
    # ### end Alembic commands ###
