"""optional config_class in source

Revision ID: 22fcfb994985
Revises: 6dd594f76aa2
Create Date: 2025-09-15 08:33:40.163270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22fcfb994985'
down_revision = '6dd594f76aa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('source', 'config_class',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('source', 'config_class',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
