"""Make allowed_origins not nullable

Revision ID: 2d0c02a35fdb
Revises: bc585d97c777
Create Date: 2025-05-18 20:03:05.507428

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2d0c02a35fdb"
down_revision = "bc585d97c777"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Set a default value for existing rows
    op.execute(
        "UPDATE white_label SET allowed_origins = 'localhost:5173,localhost:8001,localhost:8080,localhost:3000' WHERE allowed_origins IS NULL"
    )

    # Make the column not nullable
    op.alter_column("white_label", "allowed_origins", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("white_label", "allowed_origins", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
