"""drop organization name uniqueness constraint

Revision ID: 4c0a2d377923
Revises: 34b7f4f4ac81
Create Date: 2025-06-08 22:02:44.138745

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4c0a2d377923"
down_revision = "34b7f4f4ac81"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("organization_name_key", "organization", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("organization_name_key", "organization", ["name"])
    # ### end Alembic commands ###
