"""Add requires_byoc field to source table

Revision ID: 6dd594f76aa2
Revises: 813f84a976fd
Create Date: 2025-09-14 15:31:08.329581

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6dd594f76aa2"
down_revision = "813f84a976fd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with default value for existing rows
    op.add_column(
        "source", sa.Column("requires_byoc", sa.Boolean(), nullable=False, server_default="false")
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("source", "requires_byoc")
    # ### end Alembic commands ###
