"""Add DAG models

Revision ID: 7387a849ec6c
Revises: 1fb5731c172e
Create Date: 2025-02-16 13:36:47.388445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7387a849ec6c'
down_revision = '1fb5731c172e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
