"""Add cascade delete for user_organization foreign key

Revision ID: 7dfef9ba17c0
Revises: e3ff5cd5ebd7
Create Date: 2025-06-10 20:24:43.110213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dfef9ba17c0'
down_revision = 'e3ff5cd5ebd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
