"""Add cascade delete to sync_connection sync_id foreign key

Revision ID: 8881ae81b5e3
Revises: 9a528c5b6fe4
Create Date: 2025-05-06 23:25:32.662989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8881ae81b5e3'
down_revision = '9a528c5b6fe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sync_connection_sync_id_fkey', 'sync_connection', type_='foreignkey')
    op.create_foreign_key(None, 'sync_connection', 'sync', ['sync_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sync_connection', type_='foreignkey')
    op.create_foreign_key('sync_connection_sync_id_fkey', 'sync_connection', 'sync', ['sync_id'], ['id'])
    # ### end Alembic commands ###
