"""Remove auth0_org_id from user_organization

Revision ID: 89ac9c904676
Revises: 8a4bd4e801b8
Create Date: 2025-06-10 19:29:08.102156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89ac9c904676'
down_revision = '8a4bd4e801b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_organization', 'auth0_org_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_organization', sa.Column('auth0_org_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
