"""Remove primary_organization_id from User model

Revision ID: 8a4bd4e801b8
Revises: 4c0a2d377923
Create Date: 2025-06-09 10:31:48.148199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a4bd4e801b8'
down_revision = '4c0a2d377923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_primary_organization_id_fkey'), 'user', type_='foreignkey')
    op.drop_column('user', 'primary_organization_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('primary_organization_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('user_primary_organization_id_fkey'), 'user', 'organization', ['primary_organization_id'], ['id'])
    # ### end Alembic commands ###
