"""Add white_label_id to source_connection table

Revision ID: a40588dab15f
Revises: 965a6588169d
Create Date: 2025-05-18 17:00:03.325421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a40588dab15f'
down_revision = '965a6588169d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_connection', sa.Column('white_label_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'source_connection', 'white_label', ['white_label_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'source_connection', type_='foreignkey')
    op.drop_column('source_connection', 'white_label_id')
    # ### end Alembic commands ###
