"""invert_sync_source_connection_relationship

Revision ID: ae4d92024989
Revises: 5d0640367a41
Create Date: 2025-05-06 21:52:10.758291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae4d92024989'
down_revision = '5d0640367a41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('source_connection_sync_id_fkey', 'source_connection', type_='foreignkey')
    op.drop_column('source_connection', 'sync_id')
    op.add_column('sync', sa.Column('source_connection_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'sync', 'source_connection', ['source_connection_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sync', type_='foreignkey')
    op.drop_column('sync', 'source_connection_id')
    op.add_column('source_connection', sa.Column('sync_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('source_connection_sync_id_fkey', 'source_connection', 'sync', ['sync_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
