"""Add cascade delete to sync_connection sync_id

Revision ID: c1f7ba21265e
Revises: ae4d92024989
Create Date: 2025-05-06 22:22:56.038635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f7ba21265e'
down_revision = 'ae4d92024989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sync_connection_sync_id_fkey', 'sync_connection', type_='foreignkey')
    op.create_foreign_key(None, 'sync_connection', 'sync', ['sync_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sync_connection', type_='foreignkey')
    op.create_foreign_key('sync_connection_sync_id_fkey', 'sync_connection', 'sync', ['sync_id'], ['id'])
    # ### end Alembic commands ###
