"""Add bidirectional relationship between Sync and SyncDag for cascading deletion

Revision ID: e73199299bfa
Revises: 058889b56728
Create Date: 2025-05-06 23:31:51.342740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e73199299bfa'
down_revision = '058889b56728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
