"""rename auth_provider_short_name to readable_auth_provider_id

Revision ID: ed8ef1d6266f
Revises: 6649bb0cdc88
Create Date: 2025-07-14 12:27:35.282722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed8ef1d6266f'
down_revision = '6649bb0cdc88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_connection', sa.Column('readable_auth_provider_id', sa.String(), nullable=True))
    op.drop_column('source_connection', 'auth_provider_short_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_connection', sa.Column('auth_provider_short_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('source_connection', 'readable_auth_provider_id')
    # ### end Alembic commands ###
